server {
	listen 80;
	server_name localhost;

	root /var/www/html;
	index index.php index.html;

  location ~* /vendor/ {
    deny all;
    return 403;
  }

  location /api/ {
    try_files $uri $uri/ /src/zadanie1/backend/api/index.php?$query_string;
  }

  # Zadanie 4 - Laravel
  location /zadanie4 {
    return 301 /zadanie4/;
  }

  location /zadanie4/ {
    alias /var/www/html/zadanie4/public/;
    index index.php;
    try_files $uri $uri/ @zadanie4;

    location ~ \.php$ {
      fastcgi_pass php:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $request_filename;
      include fastcgi_params;
    }
  }

  location @zadanie4 {
    rewrite ^/zadanie4/(.*)$ /zadanie4/index.php?/$1 last;
  }

	location / {
		try_files $uri $uri/ /index.php$query_string;
	}

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location ~ /\.ht {
		deny all;
	}
}
